window.AppData = {
  defaultProfileId: "u5",
  demoProfileIds: ["u5", "u6"],
  users: [
    {
      id: "u1",
      name: "Mila Berger",
      homeBase: "Berlin",
      about: "Ich mag entspannte Staedtereisen, gutes Essen und klare Absprachen.",
      languages: ["Deutsch", "Englisch"],
      interests: ["Food", "Staedtereise", "Museen"],
      verified: true,
      contact: {
        email: "mila@example.local",
        phone: "+49 000 000000"
      }
    },
    {
      id: "u2",
      name: "Noah Stein",
      homeBase: "Muenchen",
      about: "Ich plane gern Roadtrips, fahre lange Strecken entspannt und teile Kosten transparent auf.",
      languages: ["Deutsch", "Englisch"],
      interests: ["Roadtrip", "Natur", "Sommer"],
      verified: true,
      contact: {
        email: "noah@example.local",
        phone: "+49 000 000001"
      }
    },
    {
      id: "u3",
      name: "Elena Russo",
      homeBase: "Koeln",
      about: "Ich reise gern fuer gutes Essen, schoene Altstaedte und kleine kreative Hotels.",
      languages: ["Deutsch", "Italienisch", "Englisch"],
      interests: ["Food", "Kultur", "Meer"],
      verified: true,
      contact: {
        email: "elena@example.local",
        phone: "+49 000 000002"
      }
    },
    {
      id: "u4",
      name: "Yasmin Keller",
      homeBase: "Hamburg",
      about: "Ich mag kurze, gut strukturierte Trips mit Natur, Bewegung und ruhiger Atmosphaere.",
      languages: ["Deutsch", "Englisch"],
      interests: ["Wandern", "Natur", "Wellness"],
      verified: false,
      contact: {
        email: "yasmin@example.local",
        phone: "+49 000 000003"
      }
    },
    {
      id: "u5",
      name: "Daniel Reuter",
      homeBase: "Dortmund",
      about: "Ich will MatchTrip so nutzen, dass sich Reisen locker und fair planen lassen. Am liebsten mag ich Meer, gute Cafes und entspannte Kommunikation.",
      languages: ["Deutsch", "Englisch"],
      interests: ["Meer", "Food", "Kurztrip"],
      verified: true,
      contact: {
        email: "daniel@example.local",
        phone: "+49 000 000004"
      }
    },
    {
      id: "u6",
      name: "Mel Winter",
      homeBase: "Essen",
      about: "Ich mag kleine Ferienhaeuser, Nordsee-Luft und Trips, die freundlich geplant sind statt stressig zu werden.",
      languages: ["Deutsch", "Englisch"],
      interests: ["Ferienhaus", "Kueste", "Natur"],
      verified: true,
      contact: {
        email: "mel@example.local",
        phone: "+49 000 000005"
      }
    }
  ],
  trips: [
    {
      id: "t1",
      hostId: "u1",
      title: "Wochenende in Prag",
      startCity: "Berlin",
      destinationCity: "Prag",
      country: "Tschechien",
      startDate: "2026-06-12",
      endDate: "2026-06-15",
      timingMode: "fixed",
      travelMode: "shared",
      arrivalMode: "train",
      departureMode: "train",
      seats: 2,
      budgetPerPerson: 120,
      lat: 50.0755,
      lng: 14.4378,
      groupType: "Single",
      audiences: ["Studenten", "Singles", "Berufstaetige"],
      styles: ["Staedtereise", "Food", "Budget"],
      notes: "Bahn, zentrale Unterkunft, viel zu Fuss und kleine Cafes. Ich suche entspannte Leute, die Planung moegen.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t2",
      hostId: "u2",
      title: "Roadtrip an den Gardasee",
      startCity: "Muenchen",
      destinationCity: "Gardasee",
      country: "Italien",
      startDate: "2026-07-03",
      endDate: "2026-07-16",
      timingMode: "flexible",
      travelMode: "shared",
      arrivalMode: "car",
      departureMode: "car",
      seats: 3,
      budgetPerPerson: 260,
      lat: 45.604,
      lng: 10.6351,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Paare", "Berufstaetige"],
      styles: ["Roadtrip", "Natur", "Meer"],
      notes: "Auto ist vorhanden. Benzin, Maut und Apartment werden geteilt. Der genaue Starttag kann im Zeitraum noch gemeinsam festgelegt werden.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t3",
      hostId: "u3",
      title: "Herbsttage in Porto",
      startCity: "Koeln",
      destinationCity: "Porto",
      country: "Portugal",
      startDate: "2026-10-01",
      endDate: "2026-10-06",
      timingMode: "fixed",
      travelMode: "solo",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 340,
      lat: 41.1579,
      lng: -8.6291,
      groupType: "Single",
      audiences: ["Singles", "Paare", "Berufstaetige"],
      styles: ["Staedtereise", "Food", "Meer"],
      notes: "Flug wird frueh gebucht, Unterkunft eher ruhig. Ich mag morgens planen und abends spontan sein. Der Trip funktioniert auch komplett solo.",
      contactUnlock: "after-request",
      status: "Offen"
    },
    {
      id: "t4",
      hostId: "u4",
      title: "Bled und Ljubljana mit dem Zug",
      startCity: "Hamburg",
      destinationCity: "Bled",
      country: "Slowenien",
      startDate: "2026-05-21",
      endDate: "2026-05-26",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "train",
      departureMode: "train",
      seats: 2,
      budgetPerPerson: 210,
      lat: 46.3692,
      lng: 14.1136,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Best Ager"],
      styles: ["Natur", "Budget", "Wandern"],
      notes: "Die Idee ist ein entspannter Mix aus See, Altstadt und leichten Wanderungen. Schlafen eher einfach, dafuer gute gemeinsame Tage. Falls es nicht matched, ist der Trip auch solo gut machbar.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t5",
      hostId: "u1",
      title: "Amsterdam fuer Museen und Grachten",
      startCity: "Dortmund",
      destinationCity: "Amsterdam",
      country: "Niederlande",
      startDate: "2026-08-14",
      endDate: "2026-08-17",
      timingMode: "fixed",
      travelMode: "shared",
      arrivalMode: "train",
      departureMode: "train",
      seats: 2,
      budgetPerPerson: 190,
      lat: 52.3676,
      lng: 4.9041,
      groupType: "Freundesgruppe",
      audiences: ["Studenten", "Freundesgruppen", "Singles"],
      styles: ["Staedtereise", "Kultur", "Food"],
      notes: "Ein kompakter Trip mit frueher Buchung, Tagesplaenen und genug Raum fuer spontane Cafes und Museen.",
      contactUnlock: "after-request",
      status: "Offen"
    },
    {
      id: "t6",
      hostId: "u4",
      title: "Wanderwoche in Suedtirol",
      startCity: "Stuttgart",
      destinationCity: "Bozen",
      country: "Italien",
      startDate: "2026-09-05",
      endDate: "2026-09-20",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "car",
      departureMode: "car",
      seats: 3,
      budgetPerPerson: 390,
      lat: 46.4983,
      lng: 11.3548,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Berufstaetige", "Best Ager"],
      styles: ["Natur", "Wandern", "Roadtrip"],
      notes: "Ich suche Leute, die frueh starten koennen, tagsueber gern draussen sind und abends lieber huettig als laut unterwegs sind. Die genauen Tage koennen wir im Zeitraum noch abstimmen. Falls niemand passt, bleibt der Trip trotzdem solo moeglich.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t7",
      hostId: "u3",
      title: "Valencia Sonne, Markt und Strand",
      startCity: "Frankfurt",
      destinationCity: "Valencia",
      country: "Spanien",
      startDate: "2026-06-18",
      endDate: "2026-06-23",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 2,
      budgetPerPerson: 430,
      lat: 39.4699,
      lng: -0.3763,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Berufstaetige"],
      styles: ["Meer", "Food", "Kultur"],
      notes: "Tagsueber Stadt und Strand, abends Tapas. Ich suche entspannte Leute mit normalem Schlafrhythmus und fairer Kostenplanung. Zur Not kann die Reise auch alleine stattfinden.",
      contactUnlock: "after-request",
      status: "Offen"
    },
    {
      id: "t8",
      hostId: "u1",
      title: "Paris in drei Tagen",
      startCity: "Koeln",
      destinationCity: "Paris",
      country: "Frankreich",
      startDate: "2026-11-06",
      endDate: "2026-11-09",
      timingMode: "fixed",
      travelMode: "solo",
      arrivalMode: "train",
      departureMode: "train",
      seats: 1,
      budgetPerPerson: 250,
      lat: 48.8566,
      lng: 2.3522,
      groupType: "Single",
      audiences: ["Studenten", "Singles", "Paare"],
      styles: ["Staedtereise", "Kultur", "Food"],
      notes: "Kurzer Intensivtrip mit fruehem Zug, guter Lage und Fokus auf kleine Restaurants, Viertelspaziergaenge und ein Museum. Ideal auch fuer bewusstes Solo-Reisen mit App-Struktur.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t9",
      hostId: "u2",
      title: "Kuestenfahrt bis Split",
      startCity: "Nuernberg",
      destinationCity: "Split",
      country: "Kroatien",
      startDate: "2026-07-22",
      endDate: "2026-08-02",
      timingMode: "flexible",
      travelMode: "shared",
      arrivalMode: "car",
      departureMode: "car",
      seats: 3,
      budgetPerPerson: 310,
      lat: 43.5081,
      lng: 16.4402,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Studenten", "Singles"],
      styles: ["Roadtrip", "Meer", "Budget"],
      notes: "Van ist da, Playlist auch. Gesucht werden Leute mit lockerer Art, die Fahrkosten sauber teilen und beim Planen mitdenken. Abfahrt und Rueckkehr koennen im Zeitraum etwas flexibel bleiben.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t10",
      hostId: "u4",
      title: "Ruhige Tage am Titisee",
      startCity: "Freiburg",
      destinationCity: "Titisee",
      country: "Deutschland",
      startDate: "2026-12-04",
      endDate: "2026-12-18",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "car",
      departureMode: "car",
      seats: 2,
      budgetPerPerson: 190,
      lat: 47.9002,
      lng: 8.1518,
      groupType: "Alleinerziehend",
      audiences: ["Alleinerziehend", "Familien", "Best Ager"],
      styles: ["Wellness", "Natur", "Budget"],
      notes: "Ruhiger Kurztrip mit entspannter Unterkunft, kurzen Wegen und genug Flexibilitaet. Die Tage koennen innerhalb des Zeitraums gemeinsam abgestimmt werden. Auch solo mit Kind oder allein planbar.",
      contactUnlock: "after-approval",
      status: "Offen"
    },
    {
      id: "t11",
      hostId: "u2",
      listingType: "request",
      title: "Flexible Anfrage fuer Holland",
      startCity: "Duesseldorf",
      destinationCity: "",
      regionLabel: "Holland",
      country: "Niederlande",
      startDate: "2026-08-01",
      endDate: "2026-08-21",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "car",
      departureMode: "car",
      seats: 1,
      budgetPerPerson: 240,
      lat: 52.1326,
      lng: 5.2913,
      groupType: "Single",
      audiences: ["Singles", "Studenten", "Berufstaetige"],
      styles: ["Meer", "Budget", "Natur"],
      notes: "Ich will im August fuer ein paar Tage nach Holland, aber noch nicht auf eine genaue Stadt festgelegt sein. Kuestennah oder ruhige Stadt passt beides.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t12",
      hostId: "u4",
      listingType: "request",
      title: "Zeeland oder ruhige Kueste mit Kind",
      startCity: "Koeln",
      destinationCity: "",
      regionLabel: "Zeeland",
      country: "Niederlande",
      startDate: "2026-07-12",
      endDate: "2026-07-28",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "car",
      departureMode: "car",
      seats: 1,
      budgetPerPerson: 280,
      lat: 51.494,
      lng: 3.8497,
      groupType: "Alleinerziehend",
      audiences: ["Alleinerziehend", "Familien"],
      styles: ["Meer", "Natur", "Budget"],
      notes: "Noch kein fixes Haus, eher ruhige Kueste mit kurzen Wegen. Ich suche nur dann eine passende Begleitung, wenn Tempo und Alltag wirklich harmonieren.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t13",
      hostId: "u6",
      title: "Mel sucht Match fuer Zeeland Haus am Meer",
      startCity: "Essen",
      destinationCity: "Zeeland",
      country: "Niederlande",
      startDate: "2026-07-18",
      endDate: "2026-07-24",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "car",
      departureMode: "car",
      seats: 1,
      budgetPerPerson: 210,
      lat: 51.4989,
      lng: 3.8405,
      groupType: "Single",
      audiences: ["Singles", "Freundesgruppen", "Berufstaetige"],
      styles: ["Meer", "Ferienhaus", "Natur"],
      notes: "Ich habe ein ruhiges Ferienhaus in Zeeland im Blick und suche genau eine Person, die entspannt, verlaesslich und offen fuer gemeinsames Planen ist.",
      contactUnlock: "after-request",
      status: "Offen"
    },
    {
      id: "t14",
      hostId: "u5",
      listingType: "request",
      title: "Daniel ist offen fuer Porto oder Lissabon",
      startCity: "Dortmund",
      destinationCity: "",
      regionLabel: "Portugal Kueste",
      country: "Portugal",
      startDate: "2026-09-03",
      endDate: "2026-09-16",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 360,
      lat: 39.3999,
      lng: -8.2245,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige"],
      styles: ["Meer", "Food", "Staedtereise"],
      notes: "Noch kein fixer Ort, aber Portugal ist gesetzt. Ich bin offen fuer Porto, Lissabon oder etwas dazwischen, wenn der Vibe passt.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t15",
      hostId: "u1",
      listingType: "request",
      title: "Tokyo im Oktober, klar geplant aber offen beim Vibe",
      startCity: "Berlin",
      destinationCity: "Tokyo",
      country: "Japan",
      startDate: "2026-10-10",
      endDate: "2026-10-24",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1180,
      lat: 35.6762,
      lng: 139.6503,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Studenten"],
      styles: ["Staedtereise", "Food", "Kultur"],
      notes: "Ich suche eine Person fuer Tokyo, die Lust auf gutes Essen, klare Tagesplaene und trotzdem genug Freiraum hat.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t16",
      hostId: "u2",
      listingType: "request",
      title: "Thailand Sueden, Insel noch offen",
      startCity: "Muenchen",
      destinationCity: "",
      regionLabel: "Thailand Sueden",
      country: "Thailand",
      startDate: "2026-11-02",
      endDate: "2026-11-24",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 2,
      budgetPerPerson: 860,
      lat: 8.0863,
      lng: 98.9063,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Singles", "Berufstaetige"],
      styles: ["Meer", "Budget", "Food"],
      notes: "Noch kein finales Inselziel. Mir geht es eher um warmes Wasser, faire Kosten und entspannte Leute ohne Dauerstress.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t17",
      hostId: "u3",
      listingType: "request",
      title: "Mexiko City oder Oaxaca, Hauptsache Kultur und Food",
      startCity: "Frankfurt",
      destinationCity: "",
      regionLabel: "Mexiko Zentrum",
      country: "Mexiko",
      startDate: "2026-09-08",
      endDate: "2026-09-23",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 980,
      lat: 19.4326,
      lng: -99.1332,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Best Ager"],
      styles: ["Food", "Kultur", "Staedtereise"],
      notes: "Ich moechte Mexiko nicht nur als Strandziel sehen, sondern richtig mit Maerkten, Museen und gutem Essen erleben.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t18",
      hostId: "u4",
      listingType: "request",
      title: "Dubai City Break mit Sonne und Struktur",
      startCity: "Hamburg",
      destinationCity: "Dubai",
      country: "VAE",
      startDate: "2026-11-14",
      endDate: "2026-11-21",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 940,
      lat: 25.2048,
      lng: 55.2708,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Berufstaetige"],
      styles: ["Staedtereise", "Food", "Wellness"],
      notes: "Ich suche einen sauberen Mix aus Skyline, Sonne, gutem Hotel und entspanntem Ablauf ohne Poser-Vibe.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t19",
      hostId: "u5",
      listingType: "request",
      title: "Malle spaetsommerlich, aber bitte ohne Ballermann",
      startCity: "Barcelona",
      destinationCity: "Palma de Mallorca",
      country: "Spanien",
      startDate: "2026-09-15",
      endDate: "2026-09-24",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "ferry",
      departureMode: "ferry",
      seats: 1,
      budgetPerPerson: 420,
      lat: 39.5696,
      lng: 2.6502,
      groupType: "Single",
      audiences: ["Singles", "Paare", "Freundesgruppen"],
      styles: ["Meer", "Food", "Natur"],
      notes: "Ich suche Mallorca mit Buchten, Marktfruehstueck und ruhiger Unterkunft statt Partyprogramm.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t20",
      hostId: "u6",
      listingType: "request",
      title: "Bali zwischen Canggu und Ubud",
      startCity: "Duesseldorf",
      destinationCity: "",
      regionLabel: "Bali",
      country: "Indonesien",
      startDate: "2026-10-28",
      endDate: "2026-11-18",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 990,
      lat: -8.65,
      lng: 115.2167,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Freundesgruppen"],
      styles: ["Meer", "Natur", "Wellness"],
      notes: "Ich will Bali eher ruhig und stilvoll machen, mit Surf oder Spa als Option und nicht nur Instagram-Orte abhaken.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t21",
      hostId: "u1",
      listingType: "request",
      title: "Seoul im Herbst fuer Food und Design",
      startCity: "Koeln",
      destinationCity: "Seoul",
      country: "Suedkorea",
      startDate: "2026-10-05",
      endDate: "2026-10-16",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1160,
      lat: 37.5665,
      lng: 126.978,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Studenten"],
      styles: ["Staedtereise", "Food", "Kultur"],
      notes: "Ich suche eine Person, die Lust auf Seoul mit Cafes, Night Markets und klarer Tagesaufteilung hat.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t22",
      hostId: "u2",
      listingType: "request",
      title: "New York im Dezember, kurz aber intensiv",
      startCity: "Stuttgart",
      destinationCity: "New York",
      country: "USA",
      startDate: "2026-12-03",
      endDate: "2026-12-10",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1250,
      lat: 40.7128,
      lng: -74.006,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Berufstaetige"],
      styles: ["Staedtereise", "Food", "Kultur"],
      notes: "Ich will New York kompakt, mit Rooftop, Deli, Museum und genug Energie fuer einen dichten City-Trip.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t23",
      hostId: "u3",
      listingType: "request",
      title: "Kapstadt zwischen Stadt, Wein und Meer",
      startCity: "Berlin",
      destinationCity: "Kapstadt",
      country: "Suedafrika",
      startDate: "2026-11-20",
      endDate: "2026-12-04",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1320,
      lat: -33.9249,
      lng: 18.4241,
      groupType: "Single",
      audiences: ["Singles", "Paare", "Berufstaetige"],
      styles: ["Meer", "Food", "Natur"],
      notes: "Mir geht es um Kapstadt mit guter Mischung aus Stadt, Kueste und Tagestrips, aber ohne gehetzten Rundreise-Modus.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t24",
      hostId: "u4",
      listingType: "request",
      title: "Island Suedkueste und Nordlichter",
      startCity: "Hamburg",
      destinationCity: "",
      regionLabel: "Island Suedkueste",
      country: "Island",
      startDate: "2026-11-01",
      endDate: "2026-11-12",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 2,
      budgetPerPerson: 980,
      lat: 63.985,
      lng: -19.057,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Paare", "Best Ager"],
      styles: ["Natur", "Roadtrip", "Wandern"],
      notes: "Noch ist nur die Region klar. Ich suche Leute mit Lust auf Natur, Wetter und ruhige Roadtrip-Abende.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t25",
      hostId: "u5",
      listingType: "request",
      title: "Madeira fuer Sonne, Wege und Remote-Vibe",
      startCity: "Dortmund",
      destinationCity: "Madeira",
      country: "Portugal",
      startDate: "2026-10-18",
      endDate: "2026-10-31",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 760,
      lat: 32.7607,
      lng: -16.9595,
      groupType: "Single",
      audiences: ["Berufstaetige", "Singles", "Best Ager"],
      styles: ["Natur", "Meer", "Wellness"],
      notes: "Ich suche Madeira eher fuer ruhige Morgen, gute Cafes und Ausfluege statt fuer Dauer-Action.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t26",
      hostId: "u6",
      listingType: "request",
      title: "Marrakesch im Riad, ruhig und kulinarisch",
      startCity: "Koeln",
      destinationCity: "Marrakesch",
      country: "Marokko",
      startDate: "2026-09-19",
      endDate: "2026-09-27",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 540,
      lat: 31.6295,
      lng: -7.9811,
      groupType: "Single",
      audiences: ["Singles", "Paare", "Berufstaetige"],
      styles: ["Food", "Kultur", "Budget"],
      notes: "Ich moechte Marrakesch mit stilvollem Riad, gutem Essen und klaren Ruhephasen statt nur Shopping-Hektik.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t27",
      hostId: "u1",
      listingType: "request",
      title: "Tulum oder Valladolid, Yucatan locker planen",
      startCity: "Frankfurt",
      destinationCity: "",
      regionLabel: "Yucatan",
      country: "Mexiko",
      startDate: "2026-11-08",
      endDate: "2026-11-22",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1040,
      lat: 20.2114,
      lng: -87.4654,
      groupType: "Single",
      audiences: ["Singles", "Freundesgruppen", "Berufstaetige"],
      styles: ["Meer", "Food", "Kultur"],
      notes: "Ich bin offen, ob es eher Strand oder koloniale Stadt wird, wichtig ist entspannter Vibe und faire Kosten.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t28",
      hostId: "u2",
      listingType: "request",
      title: "Bangkok zuerst, Insel spaeter",
      startCity: "Muenchen",
      destinationCity: "Bangkok",
      country: "Thailand",
      startDate: "2026-10-06",
      endDate: "2026-10-20",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 2,
      budgetPerPerson: 870,
      lat: 13.7563,
      lng: 100.5018,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Singles", "Studenten"],
      styles: ["Food", "Budget", "Kultur"],
      notes: "Erst Bangkok fuer Food und Tempo, danach vielleicht Strand. Noch ist nur klar, dass ich nicht alles durchplanen will.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t29",
      hostId: "u3",
      listingType: "request",
      title: "Krabi oder Phuket, aber entspannt",
      startCity: "Berlin",
      destinationCity: "",
      regionLabel: "Thailand Westkueste",
      country: "Thailand",
      startDate: "2026-12-01",
      endDate: "2026-12-17",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 920,
      lat: 8.0863,
      lng: 98.9063,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Berufstaetige"],
      styles: ["Meer", "Natur", "Budget"],
      notes: "Ich suche keine Dauerparty, sondern Meer, Bootstag und eine Unterkunft mit ruhigem Vibe.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t30",
      hostId: "u4",
      listingType: "request",
      title: "Singapur kurz, clean und urban",
      startCity: "Hamburg",
      destinationCity: "Singapur",
      country: "Singapur",
      startDate: "2026-11-05",
      endDate: "2026-11-11",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1090,
      lat: 1.3521,
      lng: 103.8198,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Best Ager"],
      styles: ["Staedtereise", "Food", "Wellness"],
      notes: "Mich reizt Singapur fuer einen sehr klaren, modernen City-Trip mit gutem Essen und wenigen, guten Stops.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t31",
      hostId: "u5",
      listingType: "request",
      title: "Abu Dhabi statt Dubai Hype",
      startCity: "Duesseldorf",
      destinationCity: "Abu Dhabi",
      country: "VAE",
      startDate: "2026-11-22",
      endDate: "2026-11-29",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 880,
      lat: 24.4539,
      lng: 54.3773,
      groupType: "Paar",
      audiences: ["Paare", "Best Ager", "Berufstaetige"],
      styles: ["Wellness", "Kultur", "Food"],
      notes: "Ich suche die ruhigere Emirate-Version mit Sonne, gutem Hotel und ein bisschen Kultur statt nur Insta-Spots.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t32",
      hostId: "u6",
      listingType: "request",
      title: "Osaka und Kyoto in einem Trip",
      startCity: "Frankfurt",
      destinationCity: "",
      regionLabel: "Kansai",
      country: "Japan",
      startDate: "2026-11-01",
      endDate: "2026-11-14",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1140,
      lat: 34.6937,
      lng: 135.5023,
      groupType: "Single",
      audiences: ["Singles", "Studenten", "Berufstaetige"],
      styles: ["Staedtereise", "Food", "Kultur"],
      notes: "Ich bin offen, wie wir Osaka und Kyoto gewichten, wichtig ist mir ein entspannter Rhythmus und gutes Essen.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t33",
      hostId: "u1",
      listingType: "request",
      title: "Mallorca mit Kind, ruhig und bezahlbar",
      startCity: "Koeln",
      destinationCity: "",
      regionLabel: "Mallorca Ostkueste",
      country: "Spanien",
      startDate: "2026-10-12",
      endDate: "2026-10-20",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 510,
      lat: 39.6953,
      lng: 3.0176,
      groupType: "Alleinerziehend",
      audiences: ["Alleinerziehend", "Familien"],
      styles: ["Meer", "Natur", "Budget"],
      notes: "Ich suche eher familienfreundliche Buchten und eine ruhige Unterkunft als grosses Programm.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t34",
      hostId: "u2",
      listingType: "request",
      title: "Ibiza ruhig statt Party",
      startCity: "Valencia",
      destinationCity: "Ibiza",
      country: "Spanien",
      startDate: "2026-09-07",
      endDate: "2026-09-14",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "ferry",
      departureMode: "ferry",
      seats: 1,
      budgetPerPerson: 460,
      lat: 38.9067,
      lng: 1.4206,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Freundesgruppen"],
      styles: ["Meer", "Wellness", "Food"],
      notes: "Ich moechte Ibiza fuer Sonnenuntergaenge, kleine Buchten und gutes Essen sehen, nicht fuer Clubs.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t35",
      hostId: "u3",
      listingType: "request",
      title: "Los Angeles, aber mit entspanntem Plan",
      startCity: "Berlin",
      destinationCity: "Los Angeles",
      country: "USA",
      startDate: "2026-10-03",
      endDate: "2026-10-15",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1330,
      lat: 34.0522,
      lng: -118.2437,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Freundesgruppen"],
      styles: ["Staedtereise", "Meer", "Food"],
      notes: "LA reizt mich nur, wenn man nicht jede Stunde verplant. Lieber gute Spots, Auto teilen und genug Ruhe dazwischen.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t36",
      hostId: "u4",
      listingType: "request",
      title: "Rio zwischen Strand und Stadt",
      startCity: "Hamburg",
      destinationCity: "Rio de Janeiro",
      country: "Brasilien",
      startDate: "2026-11-11",
      endDate: "2026-11-26",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1290,
      lat: -22.9068,
      lng: -43.1729,
      groupType: "Single",
      audiences: ["Singles", "Paare", "Berufstaetige"],
      styles: ["Meer", "Food", "Kultur"],
      notes: "Ich suche fuer Rio einen guten Mix aus Strandtagen, guten Vierteln und klarem Sicherheitsbewusstsein.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t37",
      hostId: "u5",
      listingType: "request",
      title: "Sydney irgendwann im Zeitraum, wenn es gut passt",
      startCity: "Frankfurt",
      destinationCity: "Sydney",
      country: "Australien",
      startDate: "2026-11-18",
      endDate: "2026-12-05",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1490,
      lat: -33.8688,
      lng: 151.2093,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Best Ager"],
      styles: ["Meer", "Staedtereise", "Food"],
      notes: "Australien ist eher ein grosser Wunsch als ein fixer Plan. Wenn Timing und Budgetrahmen passen, wuerde ich es wirklich angehen.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t38",
      hostId: "u6",
      listingType: "request",
      title: "Istanbul von Sofia, gern unkompliziert",
      startCity: "Sofia",
      destinationCity: "Istanbul",
      country: "Tuerkei",
      startDate: "2026-09-12",
      endDate: "2026-09-18",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "bus",
      departureMode: "bus",
      seats: 1,
      budgetPerPerson: 260,
      lat: 41.0082,
      lng: 28.9784,
      groupType: "Single",
      audiences: ["Singles", "Studenten", "Berufstaetige"],
      styles: ["Food", "Kultur", "Budget"],
      notes: "Ich moechte Istanbul unkompliziert und eher urban erleben, mit Bosporus, Essen und guter Abstimmung im Vorfeld.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t39",
      hostId: "u1",
      listingType: "request",
      title: "Athen plus eine Insel, aber noch offen welche",
      startCity: "Berlin",
      destinationCity: "",
      regionLabel: "Athen und Kykladen",
      country: "Griechenland",
      startDate: "2026-09-21",
      endDate: "2026-10-02",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 560,
      lat: 37.9838,
      lng: 23.7275,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Freundesgruppen"],
      styles: ["Meer", "Kultur", "Food"],
      notes: "Ich bin offen, ob es eher Athen plus Naxos oder etwas Aehnliches wird. Wichtig ist ein entspannter Match und faire Kosten.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t40",
      hostId: "u2",
      listingType: "request",
      title: "Kreta fuer Sonne, Haus und wenig Stress",
      startCity: "Stuttgart",
      destinationCity: "Kreta",
      country: "Griechenland",
      startDate: "2026-10-02",
      endDate: "2026-10-12",
      timingMode: "fixed",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 2,
      budgetPerPerson: 520,
      lat: 35.2401,
      lng: 24.8093,
      groupType: "Freundesgruppe",
      audiences: ["Freundesgruppen", "Paare", "Best Ager"],
      styles: ["Meer", "Natur", "Wellness"],
      notes: "Ich suche eher Ruhe, Terrasse und gute Tagesausfluege als einen vollen Inselplan.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t41",
      hostId: "u3",
      listingType: "request",
      title: "Zanzibar, wenn Unterkunft und Leute passen",
      startCity: "Frankfurt",
      destinationCity: "Zanzibar",
      country: "Tansania",
      startDate: "2026-11-06",
      endDate: "2026-11-18",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1210,
      lat: -6.1659,
      lng: 39.2026,
      groupType: "Paar",
      audiences: ["Paare", "Singles", "Best Ager"],
      styles: ["Meer", "Natur", "Wellness"],
      notes: "Ich sehe Zanzibar eher als ruhigen, schoenen Beach-Trip und moechte vorher klar wissen, ob Unterkunft und Alltag zusammenpassen.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t42",
      hostId: "u4",
      listingType: "request",
      title: "Costa Rica mit Fokus auf Natur und kleine Lodges",
      startCity: "Hamburg",
      destinationCity: "",
      regionLabel: "Costa Rica Pazifik",
      country: "Costa Rica",
      startDate: "2026-11-12",
      endDate: "2026-11-27",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1360,
      lat: 9.9281,
      lng: -84.0907,
      groupType: "Single",
      audiences: ["Singles", "Freundesgruppen", "Best Ager"],
      styles: ["Natur", "Wandern", "Meer"],
      notes: "Ich suche Costa Rica nicht als Luxusreise, sondern eher mit Natur, kleineren Unterkuenften und gutem Respekt fuer Tempo und Sicherheit.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t43",
      hostId: "u5",
      listingType: "request",
      title: "Hanoi oder Da Nang, Vietnam ist gesetzt",
      startCity: "Berlin",
      destinationCity: "",
      regionLabel: "Vietnam Nord oder Mitte",
      country: "Vietnam",
      startDate: "2026-10-26",
      endDate: "2026-11-09",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 930,
      lat: 21.0278,
      lng: 105.8342,
      groupType: "Single",
      audiences: ["Singles", "Berufstaetige", "Freundesgruppen"],
      styles: ["Food", "Kultur", "Budget"],
      notes: "Ich bin bei Vietnam offen fuer den genauen Ort, aber ich moechte gutes Essen, entspannte Tagesplaene und keine hektische Rundreise.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    },
    {
      id: "t44",
      hostId: "u6",
      listingType: "request",
      title: "Buenos Aires irgendwann im Fruehsommer dort",
      startCity: "Madrid",
      destinationCity: "Buenos Aires",
      country: "Argentinien",
      startDate: "2026-11-18",
      endDate: "2026-12-02",
      timingMode: "flexible",
      travelMode: "hybrid",
      arrivalMode: "plane",
      departureMode: "plane",
      seats: 1,
      budgetPerPerson: 1270,
      lat: -34.6037,
      lng: -58.3816,
      groupType: "Single",
      audiences: ["Singles", "Paare", "Berufstaetige"],
      styles: ["Staedtereise", "Food", "Kultur"],
      notes: "Buenos Aires reizt mich fuer einen stilvollen Stadttrip mit Cafes, Musik und genug Raum fuer spontane Tage.",
      contactUnlock: "after-request",
      status: "Anfrage offen"
    }
  ],
  stays: [
    {
      id: "s1",
      name: "Duenenhaus Zeeland",
      city: "Zeeland",
      region: "Zeeland",
      country: "Niederlande",
      type: "Ferienhaus",
      nightlyPrice: 148,
      lat: 51.5002,
      lng: 3.8426,
      requestTripIds: ["t11", "t12"],
      vibes: ["Meer", "Natur", "Familien"]
    },
    {
      id: "s2",
      name: "Canal Loft Utrecht",
      city: "Utrecht",
      region: "Holland",
      country: "Niederlande",
      type: "Apartment",
      nightlyPrice: 132,
      lat: 52.0907,
      lng: 5.1214,
      requestTripIds: ["t11"],
      vibes: ["Staedtereise", "Budget", "Singles"]
    },
    {
      id: "s3",
      name: "Surf Stay Zandvoort",
      city: "Zandvoort",
      region: "Holland",
      country: "Niederlande",
      type: "Ferienhaus",
      nightlyPrice: 176,
      lat: 52.3713,
      lng: 4.5333,
      requestTripIds: ["t11"],
      vibes: ["Meer", "Singles", "Natur"]
    },
    {
      id: "s4",
      name: "Porto Riverside Studio",
      city: "Porto",
      region: "Porto",
      country: "Portugal",
      type: "Studio",
      nightlyPrice: 124,
      lat: 41.1496,
      lng: -8.6109,
      requestTripIds: ["t3"],
      vibes: ["Food", "Staedtereise", "Solo"]
    }
  ],
  requests: [
    {
      id: "r1",
      tripId: "t1",
      applicantName: "Sina",
      message: "Ich reise gerne leicht und wuerde die Unterkunftskosten fair teilen.",
      contactMode: "fit-check",
      privacyStage: "Alias sichtbar",
      preferredWindow: "Abends ab 19 Uhr",
      nextStep: "Kurzprofil und Budgetvorstellung zuerst im App-Chat",
      status: "Offen"
    },
    {
      id: "r2",
      tripId: "t2",
      applicantName: "Jonas",
      message: "Ich uebernehme gerne Fahrten und bin sehr unkompliziert.",
      contactMode: "app-chat",
      privacyStage: "Anonym",
      preferredWindow: "Morgens",
      nextStep: "Erst Route und Kosten splitten, dann Kontaktdaten pruefen",
      status: "Offen"
    },
    {
      id: "r3",
      tripId: "t7",
      applicantName: "Lara",
      message: "Ich suche genau so einen Mix aus Stadt und Meer und plane gern mit.",
      contactMode: "contact-unlock",
      privacyStage: "Kurzprofil sichtbar",
      preferredWindow: "Nach Feierabend",
      nextStep: "Bei beidseitigem Okay wird der geschuetzte Kontakt freigeschaltet",
      status: "Offen"
    },
    {
      id: "r4",
      tripId: "t10",
      applicantName: "Mert",
      message: "Wellness und ruhige Trips passen gut zu mir. Ich bin beim Organisieren sehr verlaesslich.",
      contactMode: "fit-check",
      privacyStage: "Alias sichtbar",
      preferredWindow: "Flexible Zeiten",
      nextStep: "Zuerst Erwartungen und Tempo abgleichen, dann Familien-Details teilen",
      status: "Offen"
    },
    {
      id: "r5",
      tripId: "t13",
      applicantId: "u5",
      applicantName: "Daniel",
      message: "Hi Mel, Zeeland klingt richtig gut. Wenn du magst, koennen wir erst Haus, Kosten und Tagesrhythmus hier im Chat abgleichen.",
      contactMode: "app-chat",
      privacyStage: "Alias sichtbar",
      preferredWindow: "Heute Abend oder morgen",
      nextStep: "Chat ist offen und Unterkunft kann gemeinsam geprueft werden",
      status: "Chat offen"
    }
  ],
  chats: [
    {
      id: "c1",
      tripId: "t13",
      requestId: "r5",
      participantIds: ["u5", "u6"],
      lastMessageAt: "2026-04-09T10:18:00.000Z",
      messages: [
        {
          id: "m1",
          senderId: "u5",
          text: "Hi Mel, Zeeland klingt richtig gut. Wenn du magst, koennen wir erst Haus, Kosten und Tagesrhythmus hier im Chat abgleichen.",
          sentAt: "2026-04-09T10:12:00.000Z"
        },
        {
          id: "m2",
          senderId: "u6",
          text: "Ja sehr gern. Ich will genau erst klaeren, ob Unterkunft und Reise-Vibe passen, bevor wir irgendwas fest buchen.",
          sentAt: "2026-04-09T10:15:00.000Z"
        },
        {
          id: "m3",
          senderId: "u5",
          text: "Perfekt. Preisrahmen und Nordseehaus passen fuer mich schon mal. Lass uns als Naechstes schauen, ob wir eher ruhig oder aktiv planen.",
          sentAt: "2026-04-09T10:18:00.000Z"
        }
      ]
    }
  ],
  costPlans: [
    {
      id: "cp1",
      tripId: "t1",
      participantCount: 3,
      splitMethod: "equal-all",
      transport: 84,
      stay: 186,
      food: 60,
      extras: 30,
      note: "Bahn und Unterkunft werden zusammen gebucht. Food bleibt als gemeinsamer Richtwert sichtbar.",
      status: "Transparent"
    },
    {
      id: "cp2",
      tripId: "t2",
      participantCount: 4,
      splitMethod: "host-prepays",
      transport: 220,
      stay: 480,
      food: 160,
      extras: 80,
      note: "Maut, Benzin und Apartment zahlt zuerst der Host. Danach wird alles gleich in der Gruppe abgerechnet.",
      status: "In Klaerung"
    },
    {
      id: "cp3",
      tripId: "t10",
      participantCount: 3,
      splitMethod: "self-pay-food",
      transport: 36,
      stay: 330,
      food: 90,
      extras: 24,
      note: "Unterkunft und Fahrt werden sauber geteilt. Food und kleine Extras koennen vor Ort individuell bleiben.",
      status: "Transparent"
    }
  ]
};
